### ISSUE TITLE
Dropping scarf dependency

### ISSUE THREAD

**Issue by samsch** [stewie1570/max-concurrency#4]
Heya, we have a community push to get @scarf/scarf removed from packages. It's a data protection and library expectations issue.

There's a considerable backlog of conversation on Reactiflux #news-and-links, with a reasonable starting point here: https://discordapp.com/channels/102860784329052160/105816607976095744/727600754646450206

The conversation also included the author of scarf as well.

The result being tannerlinsley/react-query#676

Please consider this issue covering your other packages using scarf (e.g., immutable-replace).

**Comment by stewie1570** [comment]
Thanks for the issue! I’ll look into this as soon as I get some time.

**Comment by stewie1570** [comment]
v1.5.4
